/**
 * useHistory.ts
 * Hook de histórico — gerencia estado, sincronização com backend e operações CRUD.
 */
import { useState, useEffect, useCallback } from 'react';
import { toast } from 'sonner';
import { buildApiUrl, fetchWithAuth } from '../services/api';
import { HistoryItem } from '../types';

const HISTORY_STORAGE_PREFIX = 'spi-history';

const historyKey = (item: HistoryItem) =>
  item.id || item.finalName || `${item.fileName}-${item.dimensions}-${item.timestamp}`;

const isBlobUrl = (value?: string | null) => Boolean(value?.startsWith('blob:'));

const getHistoryStorageKey = () => {
  try {
    const rawUser = localStorage.getItem('user');
    if (!rawUser) return HISTORY_STORAGE_PREFIX;
    const user = JSON.parse(rawUser) as { id?: string; email?: string };
    const identity = user.id || user.email;
    return identity ? `${HISTORY_STORAGE_PREFIX}:${identity}` : HISTORY_STORAGE_PREFIX;
  } catch {
    return HISTORY_STORAGE_PREFIX;
  }
};

const readLocalHistory = (): HistoryItem[] => {
  try {
    const raw = localStorage.getItem(getHistoryStorageKey());
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    return (parsed as HistoryItem[]).map((item) => ({
      ...item,
      originalImage: isBlobUrl(item.originalImage) ? '' : item.originalImage,
      processedImage: isBlobUrl(item.processedImage) ? '' : item.processedImage,
    }));
  } catch {
    return [];
  }
};

const writeLocalHistory = (items: HistoryItem[]) => {
  try {
    const serializable = items.map((item) => ({
      ...item,
      originalImage: isBlobUrl(item.originalImage) ? '' : item.originalImage,
      processedImage: isBlobUrl(item.processedImage) ? '' : item.processedImage,
    }));
    localStorage.setItem(getHistoryStorageKey(), JSON.stringify(serializable));
  } catch {
    // ignore
  }
};

const mergeHistory = (remote: HistoryItem[], local: HistoryItem[]) => {
  const map = new Map<string, HistoryItem>();
  remote.forEach((item) => map.set(historyKey(item), item));
  local.forEach((item) => {
    const key = historyKey(item);
    const existing = map.get(key);
    if (!existing) {
      map.set(key, item);
      return;
    }
    map.set(key, {
      ...existing,
      fileName: existing.fileName || item.fileName,
      originalImage: existing.originalImage || item.originalImage || '',
      processedImage: existing.processedImage || item.processedImage,
      timestamp: existing.timestamp || item.timestamp,
      dimensions: existing.dimensions || item.dimensions,
      finalName: existing.finalName || item.finalName,
      s3Key: existing.s3Key || item.s3Key,
      s3Url: existing.s3Url || item.s3Url,
      qualityEnhanced: existing.qualityEnhanced ?? item.qualityEnhanced,
    });
  });
  return Array.from(map.values()).sort((a, b) => b.timestamp - a.timestamp);
};

export function useHistory(isAuthenticated: boolean, onLogout: () => void) {
  const [history, setHistory] = useState<HistoryItem[]>([]);

  const loadHistoryFromBackend = useCallback(async () => {
    try {
      const resp = await fetchWithAuth(buildApiUrl('/history'));

      if (!resp.ok) {
        if (resp.status === 401) return;
        console.error('Falha ao carregar histórico do backend');
        return;
      }

      const data = await resp.json();
      // API retorna { items: [...] } (paginado) ou array direto
      const images: any[] = Array.isArray(data) ? data : (data.items ?? []);

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const mapped: HistoryItem[] = images.map((img: any) => ({
        id: img.id,
        fileName: img.fileName,
        originalImage: '',
        // displayUrl is a short-lived presigned URL generated by the backend for display.
        // Falls back to s3Url (public) if presign failed.
        processedImage: img.displayUrl || img.s3Url || '',
        marketplace: img.marketplace,
        timestamp: new Date(img.createdAt).getTime(),
        dimensions: `${img.width}x${img.height}`,
        finalName: img.finalName,
        s3Key: img.s3Key,
        s3Url: img.s3Url,
      }));

      setHistory((prev) => mergeHistory(mapped, prev));
    } catch (error) {
      console.error('Erro carregando histórico:', error);
    }
  }, []);

  const handleImageProcessed = useCallback(
    (item: HistoryItem) => {
      setHistory((prev) => mergeHistory([item], prev));
      loadHistoryFromBackend();
    },
    [loadHistoryFromBackend]
  );

  // Called after S3 upload completes: replaces the local blob-URL entry with the
  // permanent server data, then re-fetches from backend to get the presigned displayUrl.
  const handleUploadComplete = useCallback(
    (localId: string, serverItem: { id: string; processedName: string; s3Key: string; s3Url: string }) => {
      setHistory((prev) =>
        prev.map((item) =>
          item.id === localId
            ? {
                ...item,
                id: serverItem.id,
                processedImage: serverItem.s3Url,
                finalName: serverItem.processedName || item.finalName,
                s3Key: serverItem.s3Key,
                s3Url: serverItem.s3Url,
              }
            : item
        )
      );
      // Re-fetch to get presigned displayUrls from the backend.
      loadHistoryFromBackend();
    },
    [loadHistoryFromBackend]
  );

  const handleDownloadFromHistory = useCallback(async (item: HistoryItem) => {
    const rawName = item.finalName || item.fileName || 'imagem';
    const fileName = rawName.replace(/\.[^.]+$/, '') + '.png';

    // Items saved to S3 have an s3Key. Use the backend presigned-URL endpoint
    // so the download works even when the bucket is private.
    if (item.s3Key) {
      try {
        const resp = await fetchWithAuth(buildApiUrl(`/history/${item.id}/download-url`));
        if (resp.ok) {
          const { url } = await resp.json();
          // S3 responds with Content-Disposition: attachment — no link.download needed.
          const link = document.createElement('a');
          link.href = url;
          document.body.appendChild(link);
          link.click();
          document.body.removeChild(link);
          return;
        }
      } catch {
        // fallthrough to direct URL
      }
    }

    // Fallback for items still in local state (blob URL or public S3 URL).
    const downloadUrl = item.s3Url || item.processedImage;
    if (!downloadUrl) {
      toast.error('URL da imagem não disponível');
      return;
    }

    try {
      const response = await fetch(downloadUrl, { mode: 'cors' });
      if (!response.ok) throw new Error('Download failed');
      const blob = await response.blob();
      const objectUrl = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = objectUrl;
      link.download = fileName;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(objectUrl);
    } catch {
      const link = document.createElement('a');
      link.href = downloadUrl;
      link.download = fileName;
      link.target = '_blank';
      link.rel = 'noopener';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }
  }, []);

  const handleDeleteFromHistory = useCallback(
    async (id: string) => {
      try {
        const resp = await fetchWithAuth(buildApiUrl(`/history/${id}`), { method: 'DELETE' });

        if (!resp.ok) {
          if (resp.status === 401) { onLogout(); return; }
          if (resp.status === 404) {
            setHistory((prev) => prev.filter((item) => item.id !== id));
            return;
          }
          const err = await resp.json().catch(() => ({}));
          throw new Error(err.error || 'Falha ao remover imagem');
        }

        setHistory((prev) => prev.filter((item) => item.id !== id));
      } catch (error) {
        toast.error(error instanceof Error ? error.message : 'Não foi possível remover a imagem.');
      }
    },
    [onLogout]
  );

  const handleClearHistory = useCallback(async () => {
    try {
      const resp = await fetchWithAuth(buildApiUrl('/history'), { method: 'DELETE' });
      if (!resp.ok) {
        if (resp.status === 401) { onLogout(); return; }
        throw new Error('Falha ao limpar histórico');
      }
      setHistory([]);
    } catch {
      toast.error('Não foi possível limpar o histórico.');
    }
  }, [onLogout]);

  const handleUpdateHistoryItem = useCallback((updatedItem: HistoryItem) => {
    setHistory((prev) => prev.map((item) => (item.id === updatedItem.id ? updatedItem : item)));
  }, []);

  // Persiste no localStorage quando history muda
  useEffect(() => {
    if (!isAuthenticated) return;
    writeLocalHistory(history);
  }, [history, isAuthenticated]);

  // Inicialização: lê localStorage e sincroniza com backend
  const init = useCallback(() => {
    const local = readLocalHistory();
    if (local.length) setHistory(local);
    loadHistoryFromBackend(); // eslint-disable-line react-hooks/exhaustive-deps
  }, [loadHistoryFromBackend]);

  return {
    history,
    setHistory,
    init,
    loadHistoryFromBackend,
    handleImageProcessed,
    handleUploadComplete,
    handleDownloadFromHistory,
    handleDeleteFromHistory,
    handleClearHistory,
    handleUpdateHistoryItem,
  };
}
